"use client";

import { FormEvent, useState } from "react";

type Lang = "en" | "ar";

const content = {
  en: {
    nav: ["Solutions", "Technology", "About", "Case Studies", "Contact"],
    heroEyebrow: "INTELLIGENT SYSTEMS / 2026", heroTitle: <>Engineering <em>Tomorrow&apos;s</em> Intelligent Systems.</>, heroText: "NAIFUZU transforms complex data into secure, scalable technology that moves ambitious businesses forward.", explore: "Explore Solutions", vision: "Watch Our Vision",
    solutionsLabel: "01 / SOLUTIONS", solutionsTitle: <>Technology with a <em>purpose.</em></>, solutionsText: "From intelligence to infrastructure, we build systems designed to perform in the real world.",
    solutions: [["01", "AI & Machine Learning", "Predictive intelligence and autonomous systems that turn complex data into decisions."],["02", "Cybersecurity", "Proactive protection, resilient architecture and security designed for tomorrow’s threats."],["03", "Cloud Infrastructure", "Scalable, fault-tolerant infrastructure engineered for performance and continuous growth."],["04", "IoT & Connectivity", "Connect physical and digital environments through intelligent devices, data and automation."]],
    techLabel: "02 / TECHNOLOGY", techTitle: <>Built for the future.<br/><em>Ready now.</em></>, techText: "NAIFUZU combines artificial intelligence, secure cloud systems, connected devices and data engineering into one technology vision.", techList: ["Intelligence by design", "Security at every layer", "Infrastructure that scales"],
    aboutLabel: "03 / ABOUT NAIFUZU", aboutTitle: <>Built for the Future,<br/><em>Not Just the Present.</em></>, aboutText: "We don&apos;t just solve today&apos;s challenges. We build the platforms, systems and digital foundations that can define the next decade.",
    casesLabel: "04 / CASE STUDIES", casesTitle: <>Ideas that become <em>impact.</em></>,
    contactLabel: "05 / START A CONVERSATION", contactTitle: <>Let&apos;s build<br/><em>what&apos;s next.</em></>, contactText: "Tell us what you&apos;re building. Our team will get back to you to explore the right technology path.", response: "RESPONSE TIME", responseValue: "Within 1 business day", name: "Name", namePh: "Your name", email: "Email", emailPh: "you@company.com", company: "Company", companyPh: "Company name", brief: "Project brief", briefPh: "Tell us about your project...", send: "Send Request", success: "Request prepared successfully. Your email app will open to send it.", errors: {name: "Please enter your name.", email: "Please enter a valid email.", company: "Please enter your company.", message: "Tell us a little more (10 characters minimum)."}, menu: "MENU / 01", live: "● LIVE", start: "Start a conversation →", footer: "Technology for Tomorrow.", operational: "All systems operational."
  },
  ar: {
    nav: ["الحلول", "التكنولوجيا", "من نحن", "دراسات الحالة", "اتصل بنا"], heroEyebrow: "الأنظمة الذكية / 2026", heroTitle: <>نُهندس <em>أنظمة</em> المستقبل الذكية.</>, heroText: "تُحوّل NAIFUZU البيانات المعقدة إلى تقنيات آمنة وقابلة للتوسع، تساعد الشركات الطموحة على التقدم.", explore: "اكتشف حلولنا", vision: "شاهد رؤيتنا",
    solutionsLabel: "01 / الحلول", solutionsTitle: <>تكنولوجيا <em>بهدف.</em></>, solutionsText: "من الذكاء إلى البنية التحتية، نبني أنظمة مصممة لتقديم أداء حقيقي في العالم.", solutions: [["01", "الذكاء الاصطناعي والتعلم الآلي", "أنظمة ذكية تنبؤية تحول البيانات المعقدة إلى قرارات واضحة."],["02", "الأمن السيبراني", "حماية استباقية وبنية مرنة مصممة لمواجهة تهديدات المستقبل."],["03", "البنية التحتية السحابية", "بنية قابلة للتوسع وموثوقة، مصممة للأداء والنمو المستمر."],["04", "إنترنت الأشياء والاتصال", "نربط البيئات الرقمية والمادية عبر الأجهزة والبيانات والأتمتة."]],
    techLabel: "02 / التكنولوجيا", techTitle: <>مبني للمستقبل.<br/><em>جاهز الآن.</em></>, techText: "تجمع NAIFUZU بين الذكاء الاصطناعي، الأنظمة السحابية الآمنة، الأجهزة المتصلة وهندسة البيانات في رؤية تقنية واحدة.", techList: ["الذكاء في صميم التصميم", "الأمان في كل طبقة", "بنية تحتية تتوسع معك"], aboutLabel: "03 / من نحن", aboutTitle: <>نبني للمستقبل،<br/><em>وليس للحاضر فقط.</em></>, aboutText: "لا نكتفي بحل تحديات اليوم، بل نبني المنصات والأنظمة والأسس الرقمية التي يمكن أن ترسم ملامح العقد القادم.", casesLabel: "04 / دراسات الحالة", casesTitle: <>أفكار تتحول إلى <em>أثر.</em></>,
    contactLabel: "05 / ابدأ محادثة", contactTitle: <>لنبنِ معاً<br/><em>ما هو قادم.</em></>, contactText: "أخبرنا بما تعمل عليه، وسيتواصل معك فريقنا لاستكشاف المسار التقني المناسب.", response: "مدة الرد", responseValue: "خلال يوم عمل واحد", name: "الاسم", namePh: "اسمك الكامل", email: "البريد الإلكتروني", emailPh: "you@company.com", company: "الشركة", companyPh: "اسم الشركة", brief: "نبذة عن المشروع", briefPh: "أخبرنا عن مشروعك...", send: "إرسال الطلب", success: "تم تجهيز الطلب بنجاح. سيفتح تطبيق البريد لإرسال الرسالة.", errors: {name: "يرجى إدخال اسمك.", email: "يرجى إدخال بريد إلكتروني صحيح.", company: "يرجى إدخال اسم الشركة.", message: "أخبرنا بالمزيد (10 أحرف على الأقل)."}, menu: "القائمة / 01", live: "● مباشر", start: "ابدأ محادثة ←", footer: "تكنولوجيا من أجل الغد.", operational: "جميع الأنظمة تعمل."
  }
} as const;

export default function Home() {
  const [lang, setLang] = useState<Lang>("en"); const [errors, setErrors] = useState<Record<string, string>>({}); const [sent, setSent] = useState(false); const t = content[lang]; const isAr = lang === "ar"; const hrefs = ["#solutions", "#technology", "#about", "#cases", "#contact"];
  function switchLanguage() { setLang(isAr ? "en" : "ar"); setErrors({}); setSent(false); }
  function validate(form: HTMLFormElement) { const data = new FormData(form); const name = String(data.get("name") || "").trim(); const email = String(data.get("email") || "").trim(); const company = String(data.get("company") || "").trim(); const message = String(data.get("message") || "").trim(); const next: Record<string, string> = {}; if (name.length < 2) next.name = t.errors.name; if (!/^\S+@\S+\.\S+$/.test(email)) next.email = t.errors.email; if (company.length < 2) next.company = t.errors.company; if (message.length < 10) next.message = t.errors.message; return next; }
  function handleSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const next = validate(form); setErrors(next); if (Object.keys(next).length) return; const data = new FormData(form); const subject = encodeURIComponent(`NAIFUZU demo request — ${data.get("company")}`); const body = encodeURIComponent(`Name: ${data.get("name")}\nEmail: ${data.get("email")}\nCompany: ${data.get("company")}\n\n${data.get("message")}`); window.location.href = `mailto:hello@naifuzu.com?subject=${subject}&body=${body}`; setSent(true); form.reset(); }
  const langButton = { border: "1px solid rgba(0,255,240,.35)", background: "rgba(7,17,29,.8)", color: "#00fff0", minWidth: 42, height: 42, padding: "0 10px", cursor: "pointer", font: "600 11px Inter", letterSpacing: ".08em" } as const;

  return <main dir={isAr ? "rtl" : "ltr"}>
    <div className="grid-bg" />
    <nav className="nav">
      <a className="brand" href="#top"><span>N</span> NAIFUZU</a>
      <div className="navlinks">{t.nav.map((label, i) => <a href={hrefs[i]} key={label}>{label}</a>)}</div>
      <div className="nav-actions" style={{display:"flex",alignItems:"center",gap:"10px"}}><button className="lang-switch" style={langButton} onClick={switchLanguage} aria-label="Switch language">{isAr ? "EN" : "عربي"}</button><a className="navcta" href="#contact">{isAr ? "احجز عرضاً" : "Book a Demo"} <b>↗</b></a></div>
      <details className="mobile-menu"><summary aria-label="Open navigation"><span></span><span></span><span></span></summary><div className="mobile-drawer"><div className="drawer-top"><span>{t.menu}</span><span className="live-dot">{t.live}</span></div><button className="mobile-language" style={langButton} onClick={switchLanguage}>{isAr ? "English" : "العربية"}</button><div className="mobile-links">{t.nav.map((label, i) => <a href={hrefs[i]} key={label}><small>0{i + 1}</small><span>{label}</span><b>↗</b></a>)}</div><div className="drawer-bottom"><span>NAIFUZU / 2026</span><a href="#contact">{t.start}</a></div></div></details>
    </nav>

    <section id="top" className="hero section"><div className="hero-copy"><div className="eyebrow"><i /> {t.heroEyebrow}</div><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="actions"><a className="primary" href="#solutions">{t.explore} <span>→</span></a><a className="secondary" href="#technology">{t.vision} <span>◉</span></a></div></div><div className="hero-orb" aria-hidden="true"><div className="orb-core">N</div><div className="ring r1" /><div className="ring r2" /><div className="ring r3" /><div className="node n1"/><div className="node n2"/><div className="node n3"/></div></section>
    <section id="solutions" className="section"><div className="section-head"><div><span className="label">{t.solutionsLabel}</span><h2>{t.solutionsTitle}</h2></div><p>{t.solutionsText}</p></div><div className="cards">{t.solutions.map(([n,title,text])=><article className="card" key={n}><span className="number">{n}</span><div className="mini-icon">↗</div><h3>{title}</h3><p>{text}</p><a href="#contact">{isAr ? "اكتشف" : "Discover"} <span>→</span></a></article>)}</div></section>
    <section id="technology" className="tech section"><div className="tech-visual"><div className="scanline"/><div className="tech-n">N</div><div className="data data1">01001001 00110110<br/>10110010 01101001<br/>11001010 00101101</div><div className="data data2">AI_CORE // ONLINE<br/>SECURE_NODE // ACTIVE<br/>SYSTEM_01 // READY</div></div><div className="tech-copy"><span className="label">{t.techLabel}</span><h2>{t.techTitle}</h2><p>{t.techText}</p><div className="tech-list">{t.techList.map((item, i)=><div key={item}><b>0{i+1}</b> {item}</div>)}</div></div></section>
    <section id="about" className="section about"><span className="label">{t.aboutLabel}</span><h2>{t.aboutTitle}</h2><p className="wide">{t.aboutText}</p></section>
    <section className="metrics section">{[["99.99%",isAr?"وقت التشغيل":"Uptime"],["50+",isAr?"براءة اختراع عالمية":"Global Patents"],["$1.2B",isAr?"قيمة العملاء":"Client Value"],["120+",isAr?"عميل مؤسسي":"Enterprise Clients"]].map(([a,b])=><div className="metric" key={b}><strong>{a}</strong><span>{b}</span></div>)}</section>
    <section id="cases" className="section cases"><div className="section-head"><div><span className="label">{t.casesLabel}</span><h2>{t.casesTitle}</h2></div></div><div className="case-grid"><div className="case"><span>AI / ENTERPRISE</span><h3>{isAr ? "منصة الذكاء التنبؤي" : "Predictive Intelligence Platform"}</h3><p>{isAr ? "تحويل البيانات التشغيلية المتفرقة إلى ذكاء أعمال لحظي." : "Turning fragmented operational data into real-time business intelligence."}</p><b>{isAr ? "عرض الحالة ←" : "View case →"}</b></div><div className="case"><span>SECURITY / CLOUD</span><h3>{isAr ? "بنية رقمية مرنة وآمنة" : "Resilient Digital Infrastructure"}</h3><p>{isAr ? "هندسة تضع الأمان أولاً ومصممة للتوفر العالي والتوسع." : "Security-first architecture engineered for high availability and scale."}</p><b>{isAr ? "عرض الحالة ←" : "View case →"}</b></div></div></section>
    <section id="contact" className="contact-section section"><div className="contact-intro"><span className="label">{t.contactLabel}</span><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="contact-meta"><span>{t.response}</span><b>{t.responseValue}</b></div></div><form className="contact-form" onSubmit={handleSubmit} noValidate><label>{t.name}<input name="name" autoComplete="name" placeholder={t.namePh} aria-invalid={!!errors.name}/>{errors.name && <small>{errors.name}</small>}</label><label>{t.email}<input name="email" type="email" autoComplete="email" placeholder={t.emailPh} aria-invalid={!!errors.email}/>{errors.email && <small>{errors.email}</small>}</label><label>{t.company}<input name="company" autoComplete="organization" placeholder={t.companyPh} aria-invalid={!!errors.company}/>{errors.company && <small>{errors.company}</small>}</label><label>{t.brief}<textarea name="message" rows={5} placeholder={t.briefPh} aria-invalid={!!errors.message}/>{errors.message && <small>{errors.message}</small>}</label><button className="primary form-submit" type="submit">{t.send} <span>↗</span></button>{sent && <p className="success" role="status">{t.success}</p>}</form></section>
    <footer><div className="brand"><span>N</span> NAIFUZU</div><p>{t.footer}</p><div className="footer-links"><a href="#">LinkedIn</a><a href="#">X</a><a href="#">GitHub</a><a href="mailto:hello@naifuzu.com">Email</a></div><small>© 2026 NAIFUZU. {t.operational}</small></footer>
  </main>;
}
